version: '3.8'
services:
  backend:
    container_name: backend
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./backend/app:/app
    ports:
      - "80:80"