"""added is_email-confirmed field on user table

Revision ID: e5af05ce0df5
Revises: 44e125d5e34a
Create Date: 2024-03-24 15:06:13.531667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5af05ce0df5"
down_revision: Union[str, None] = "44e125d5e34a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_email_confirmed", sa.Boolean(), nullable=True, default=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_email_confirmed")
    # ### end Alembic commands ###
