"""added is for change field on email confirmation tokens table

Revision ID: f3cb8c9ca7d9
Revises: ecb53487a152
Create Date: 2024-03-26 14:34:31.974949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3cb8c9ca7d9"
down_revision: Union[str, None] = "ecb53487a152"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_confirmation_tokens",
        sa.Column("is_for_change", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_confirmation_tokens", "is_for_change")
    # ### end Alembic commands ###
