"""added extra data field on email confirmation tokens table

Revision ID: 3706121127fe
Revises: f3cb8c9ca7e9
Create Date: 2024-03-26 16:27:09.029169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3cb8c9ca7e9"
down_revision: Union[str, None] = "f3cb8c9ca7d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_confirmation_tokens", sa.Column("extra_data", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_confirmation_tokens", "extra_data")
    # ### end Alembic commands ###
